### ISSUE TITLE
Only the first "Ready to search" entry in series should be translated to "enable listing"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/okapi#333]
```
What steps will reproduce the problem?
1. Compare GPX and OKAPI output for OC10CB8, especially the log by Linusus as 
of June 2nd
2. In GPX, it is owner maintenance, in OKAPI it is enable listing.

This has confused some users of c:geo, see 
https://github.com/cgeo/cgeo/issues/5004

However, from outside I cannot really judge if this is an OKAPI bug or a bug in 
the GPX export of OC.DE.
```

Original issue reported on code.google.com by `bananewe...@gmail.com` on 7 Jun 2015 at 5:01

**Comment by following5** [comment]
> > Am I correct in assuming that for OCDE GPX files produced by OKAPI all such 
entries are currently translated as "enable listing"?

> True. 

Maybe I misunderstood the question. OKAPI writes Opencaching log types into GPX files, i.e. "Ready to search". Then it's c:geo which [translates](https://github.com/cgeo/cgeo/blob/95af44fea12e0b50fe84fd3562c91624219dcb52/main/src/cgeo/geocaching/connector/oc/OkapiClient.java#L679) that to "Enable listing". 

This is a c:geo issue. "Ready to search" should be displayed as "Ready to search" instead of translating it into an inappropriate Groundspeak term.
