### ISSUE TITLE
Feature request: allow registration of new users using OKAPI functionality

### ISSUE THREAD

**Issue by ebillen** [opencaching/okapi#355]
If OKAPI allows the registration of new users, mobile OKAPI clients like c:geo could offer the creation of a new user directly from the app, without the user having to register on the website.
A new user who downloaded an app like c:geo because he likes to try this "geocatching thing" ;-) could be directed to opencaching nodes then instead of starting his/her geocaching career on a commercial platform.

See also: https://github.com/cgeo/cgeo/issues/5364

**Comment by wrygiel** [comment]
I't more difficult that you'd think.

OC sites differ from one another. E.g. some of them may require different fields to be filled upon registration, and it would be impossible to keep these requirements backward compatible. In other words, both OKAPI and its clients would need to exchange a structure resembling a HTML form, and the form cound contain JavaScript (e.g. for reCaptcha).

It would be MUCH easier to simply point the user to the "register" page.

**Comment by following5** [comment]
> E.g. some of them may require different fields to be filled upon registration, and it would be impossible to keep these requirements backward compatible.

That's all true also for submitting logs. And the compatibility issue is solved by delegating it to the OC nodes. We already had change requests at OC.de that we had to reject because they cannot be implemented backwards compatible in OKAPI. Such restrictions were expected and agreed upon by the OC.de team when we introduced OKAPI.

But I agree, the simplest way is using the site's registration page. Then, it would make sense to add an OKAPI method which returns the URL of the registration page. Or two URLs: A basic page, and a mobile-optimized page if available.

**Comment by following5** [comment]
Better: add fields to apisrv/installation for the registration page URLs.

**Comment by wrygiel** [comment]
> Better: add fields to apisrv/installation for the registration page URLs.

Good idea.

> Or two URLs: A basic page, and a mobile-optimized page if available.

I think one link is enough. Most modern sites can dynamically decide this by themselves.

**Comment by following5** [comment]
Ever seen a modern OC site? ;)

**Comment by wrygiel** [comment]
Nope. ;) Okay, if you want, you may add two of them. :)

**Comment by following5** [comment]
@ebillen
Are you comfortable with this solution?

**Comment by ebillen** [comment]
@following5, @wrygiel: yes, I am comfortable with that.
Thanks to you guys for all the good work you are doing regarding the OKAPI!
