### ISSUE TITLE
search/all - not_found_by produces strange result

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#357]
I would expect that suppliying the not_found_by option will return a list of caches with DNF logs by the given user(s). Instead, it returns a gigantic list of all caches which have *no found logs* by that user(s).

Is this intentional? If not, can we change the semantics without breaking compatibility?

**Comment by following5** [comment]
Same issue with the found_status option.

**Comment by wrygiel** [comment]
Yes, it's intentional, and seems very needed. E.g. you want to display only the caches you haven't yet found.

After we allow pipe-separated value it will be even more useful. Say, you're going on a trip with fellow geocachers, but you want to visit only such geocaches which NONE of you have previously found.

This semantics seems sound for me.

**Comment by following5** [comment]
Ok, that makes sense. It is also implemented that way in the OC search and map filters.
