### ISSUE TITLE
Error message is not supplied as XML

### ISSUE THREAD

**Issue by RoffelKartoffel** [opencaching/okapi#372]
If the user supplies an invalid token, 
https://www.opencaching.de/okapi/services/users/user?format=xmlmap2&fields=uuid 
responds with 

{"error":{"developer_message":"Invalid access token: tbauhNULrMBgZsfpz9cV.","reason_stack":["invalid_oauth_request","invalid_token"],"status":401,"more_info":"http:\/\/opencaching.pl\/okapi\/introduction.html#errors"}}

instead of XML.

**Comment by wrygiel** [comment]
This is expected and cannot be changed without breaking backward compatibility. Excerpt from the docs:

> (...) This description will be always formatted in JSON (regardless of the format parameter you might have used in your request). (...)

As to the "why": This seemed to be the safest option. Please note that in some circumstances OKAPI may not be able to access the "format" parameter (e.g. invalid value of the parameter, or invalid URL encoding, or invalid HTTP method, etc.). In these cases OKAPI would still respond with JSON, because it would not know that the client prefers XML. That's why we require all clients to expect all errors to be described in JSON.

**Comment by RoffelKartoffel** [comment]
Thank you for the information. Sadly this seems to make the usage of an XML parser on the client nonsensical since JSON is required either way. Please close this "issue", if you intend to keep it this way.

**Comment by wrygiel** [comment]
> JSON is required either way.

Unfortunately, yes (if you intend to parse error responses).

I will close it, because I cannot see any "proper" way of changing this behavior - regardless of what we did, there still would be many kinds of bad requests for which JSON would be returned.
