### ISSUE TITLE
Get rid of transaction spam?

### ISSUE THREAD

**Issue by wrygiel** [opencaching/okapi#388]
Recently we're getting more of these on OCPL:

* SQL Error 1213: Deadlock found when trying to get lock; try restarting transaction
* SQL Error 1205: Lock wait timeout exceeded; try restarting transaction

I'm not sure if these kinds of errors can be avoided. If not, then we should silent them. E.g. OKAPI could count their occurrences and report only an aggregated number of such, if some predefined MAX value was exceeded...

**Comment by following5** [comment]
I would not feel comfortable with deadlocks completely muted. They usually are caused by a race condition in database transactions and should be avoided by improving the code. Or may be muted for single SQL statments, which are uncritical when failing...?

```
                    replace into okapi_tile_caches (
                        z, x, y, cache_id, z21x, z21y, status, type, rating,
                        flags, name_crc
                    )
                    select
                        '4',
                        '8',
                        '5',
                        cache_id, z21x, z21y, status, type, rating,
                        flags, name_crc
                    from okapi_tile_caches
                    where
                        z = '3'
                        and x = '4'
                        and y = '2'
                        and z21x between 260046848 and 310378496
                        and z21y between 159383552 and 209715200
```
This statement both reads from and writes to the same table. While writing, the table will be locked for any other access. There must be some SQL running concurrently which

**Comment by wrygiel** [comment]
I think that part of your message got cut off ("There must be some SQL running concurrently which").

**Comment by following5** [comment]
Hit the comment button to early, have completet it above.

**Comment by following5** [comment]
Let's assume this statement runs concurrently on two connnections.

1. Connection 1 starts to read from `okapi_tile_caches`. While reading, the table is locked for write access.
2. Connection 2 also starts to read from `okapi_tile_caches` and creates an additional write lock on the table.
3. Connection 1 now wants to write to the table, but must wait because of the write lock by connection 2.
4. Now what happens when Connection 2 wants to start writing? Will it release its write lock first, so that connection 1 can continue? Maybe not. Then we have a deadlock.

This may be tested by running two expensive statements of that kind concurrently in two threads (two PHP scripts started nearly simultaneously).

**Comment by wrygiel** [comment]
Related comment from the source code:

```
        # Note, that multiple threads may try to compute tiles simulatanously.
        # For low-level tiles, this can be expensive. WRTODO: Think of some
        # appropriate locks.
```

**Comment by wrygiel** [comment]
Damn, I know you're right, but I don't have time for this :(

**Comment by following5** [comment]
This should be easy to fix by placing a lock around the statement. I can try, tilemap is running on my OCPL devel site.

**Comment by wrygiel** [comment]
AFAIR, putting a generic lock there would prevent concurrent rendering of tiles. I'm afraid we would need a lock for each (x,y,z)...

**Comment by following5** [comment]
>  I'm afraid we would need a lock for each (x,y,z)...

Why not? A lock should not be expensive. The server will just set and reset some semaphore.

**Comment by wrygiel** [comment]
Yes, I guess you're right.

**Comment by following5** [comment]
> But that's a global lock. Exactly the one I didn't want ;)
...
> But let's leave it for now. Once the tilecache is built, this should slow down things much. (But if the tilecache is purged, then this might make rebuilding it much slower.)

I guess it will not be noticably slower, because there already were implicit locks. When a concurrent SQL started, it either needed to wait for the previous SQLto  finish `replace`ing, or both ran into a deadlock.

The following code would avoid locks and allow concurrency as far as possible, but overall I don't think it will speed up anything.

```
                Db::execute("
                    create temporary table okapi_tile_caches_temp engine=memory
                    select
                        '".Db::escape_string($zoom)."' z,
                        '".Db::escape_string($x)."' x,
                        '".Db::escape_string($y)."' y,
                        cache_id, z21x, z21y, status, type, rating,
                        flags, name_crc
                    from okapi_tile_caches tc2
                    where
                        z = '".Db::escape_string($parent_zoom)."'
                        and x = '".Db::escape_string($parent_x)."'
                        and y = '".Db::escape_string($parent_y)."'
                        and z21x between $left_z21x and $right_z21x
                        and z21y between $top_z21y and $bottom_z21y
                ");
                Db::execute("
                    replace into okapi_tile_caches (
                        z, x, y, cache_id, z21x, z21y, status, type, rating,
                        flags, name_crc
                    )
                    select * from okapi_tile_caches_temp
                ");
                Db::execute("
                    drop temporary table okapi_tile_caches_temp
                ");

```

**Comment by following5** [comment]
Sry, I was not aware of local locking. Concurrent reading of rows from MyISAM tables while appending new rows to the end of the table (not filling gaps inbetween) will work. So - yes - the global lock probably makes it slower. And the code snipped above, which avoids both locks and deadlocks, should help!

Memory usage for the temp tables should be ok, a few MB for each bundle of concurrent connections of one map view.
