### ISSUE TITLE
[Security] Vulnerability by $_COOKIE through unzerialize()

### ISSUE THREAD

**Issue by Rotzbua** [opencaching/okapi#438]
- Object Injection
- https://www.owasp.org/index.php/PHP_Object_Injection
- affects all OC versions
- replace serialize by json_decode/encode -> then also usable by javascript

okapi/OCSession
function get_user_id()

``` php
$OC_data = unserialize(base64_decode($_COOKIE[$cookie_name]));
```

**Comment by wrygiel** [comment]
Sorry for the late reply, I've been on vacation for the last two weeks. Returned just now.

I wasn't aware of the fact that `serialize` works with objects. Thanks!

BTW, this piece of code was copied from the original OCPL code, in order to allow OKAPI to detect which user is signed in. So, this will need to be changed in OCPL code too.

**Comment by wrygiel** [comment]
As I understand the code, OKAPI will attempt to retrieve the same cookie in OCDE environment too. Are you planning on making it JSON for OCDE?

**Comment by wrygiel** [comment]
Forgot to close this. It has been already fixed for OCDE, and also a bit safer `unserialize` call was applied for OCPL, but there's nothing more we can do here, until OCPL changes the cookie format.

https://github.com/opencaching/okapi/commit/d148501e24eeacdb115235a455d35219e0c446fb#diff-0a7824867b8bd3d090d453e5fdd27ea8R65
