### ISSUE TITLE
okapi updates last_login column even if user is not logged

### ISSUE THREAD

**Issue by kojoty** [opencaching/okapi#439]
@harrieklomp  discovered an issue:
https://github.com/opencaching/opencaching-pl/issues/724
and it seems that the reason is last_login update in service_runner.php::call()

I'm not sure how to deal with it...

**Comment by wrygiel** [comment]
The `last_login` update was added by @following5 in commit ec561d20. In issue #337 is has been stated that:

> The user.last_login field has the meaning of "last activity"

This seems to be a valid definition, I think. Also, [`Facade` docs](https://github.com/opencaching/okapi/blob/5e29f2e4421553312b085993c1fdab9e97d10363/okapi/facade.php#L49) say:

> If you want to simulate Level 3 Authentication, you should supply user's internal ID (the second parameter).

So, whenever `Facade::service_call` is called with non-null user_id, OKAPI assumes that it is **this user_id** who called it. However, in case of OCPL's feature of "peeking at other user's map", this is not true.

So, I believe we have two problems here:

* OCPL doesn't properly state that it is *not* the user who is making this call.
* OKAPI doesn't allow OCPL to state the above.

**Comment by wrygiel** [comment]
The way OCPL is calling OKAPI causes some other questions to arise too. For example, is it okay that user X is allowed to see that user Y is ignoring geocache Z? (I think not. It seems to be private data. But currently it is accessible to everyone.)

**Comment by wrygiel** [comment]
For now, I think we should fix it this way:

**Before:** OKAPI was updating `last_login` value on *every* Level 3 request.
**Now:** OKAPI will be updating `last_login` only when Level 3 request is used on *selected methods* (the ones that actually "change" something).

**Comment by following5** [comment]
> Now: OKAPI will be updating last_login only when Level 3 request is used on selected methods (the ones that actually "change" something).

`last_login` is an important information about if a user is still active on the OC site or not. E.g. at OC.de, if there are problems with a user's caches, it may be immediatly archived if the user is inactive, while active users will be contacted by email, or we even may assume that the user is aware of the problems and won't take any action.

Therfore this field should be updated on any user activity, not only calling methods which may change data!

I undestand that here is some problem with the internal OKAPI usage at OCPL, therefore as a quick fix, I will revert this for OCDE only.

**Comment by following5** [comment]
On the other hand: If a user just useses OKAPI authentication but does not add/edit any content, this indeed may be some automatic activity. E.g. automatic "login" through some mobile App which was granted access to the OC site, but which is not really used for OC activity.

(I had in mind the manual login at the website, which indicates that a user is identionally accessing Opencaching, but OKAPI activity can be something else.)

So, this change may be a good solution.

**Comment by andrixnet** [comment]
IMO:
1. website login is a certain indicator of activity.
2. OKAPI activity that adds/changes data (such as posting a log) is a certain indicator of activity
3. OKAPI activity that retrieves data only (get cache data, get caches for a map display or list) may or may not be user activity. 

In the context of the report by @harrieklomp if userA looks at the map with data retrieved by OKAPI of a cache owned by userX, that is activity for userA, **not** userX.

**Comment by following5** [comment]
The original OKAPI impementation was this:

* Any OKAPI activity _by an authentified user_ is user activity and updates the `login_date` field.

This now has been changed to (2), discarding any read-only user activity. So if a cache owner now regularly checks the logs of his caches via OKAPI, but does not change or log any caches, the website will wrongly show the user as inactive. The original implementation was correctly showing theuser as active.

(I keep the ticket open now, maybe we can still find a better solution for this.)

>  if userA looks at the map with data retrieved by OKAPI of a cache owned by userX, that is activity for userA, not userX.

Yes. But the problem here is that in OCPL code, userA pretends to be userX when accessing some userX data, therefore the login date of userX was updated. **The identity of userX is faked.** This should never be necessary. Any public data of userX should be accessible trough level 1 OKAPI method, not needing authentication. Any non-public data of userX should not be accessible for userA!

**Comment by following5** [comment]
> if a cache owner now regularly checks the logs of his caches via OKAPI, but does not change or log any caches, the website will wrongly show the user as inactive. 

Of course, the owner needs not to log in to check his caches. But will usually do so on the OC website, because the easiest way to access the own caches is from the user's menu "my caches" list, which needs login.

Workflow on an OKAPI client app may be different. After granting access, the app may regularly access the user's data at the OC site, though the user is viewing and searching only GC caches. So `last_login` would be updated, but the user is not really active, just technically ...

**Comment by following5** [comment]
Another example ist issue #488. There will be some automatic process that changes log passwords of caches on behalf of the owner. This will update `last_login` as long this process is running, also with the new implementation. Is this "user activity"?

But that's a general problem. There are also automated tools that log in at the OC website.

**Comment by following5** [comment]
> The way OCPL is calling OKAPI causes some other questions to arise too. For example, is it okay that user X is allowed to see that user Y is ignoring geocache Z? (I think not. It seems to be private data. But currently it is accessible to everyone.)

I have opened an OCPL issue for this: https://github.com/opencaching/opencaching-pl/issues/1169
