### ISSUE TITLE
A70 and A71 should be merged

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#445]
Both A70 and A71 refer to one attribute: Recommended for children, cache poses no dangers, puzzles can be solved by school children.
More to the point, A70 should be merged into A71. Afterwards, the A codes could be renumbered. 

Bringing OCUK to current has highlighted the fact this (and other) attribute(s) is(are) duplicated and complicate things with ID overlaps.
I have already changed OCRO to match A71.

**Comment by wrygiel** [comment]
> Both A70 and A71 refer to one attribute

AFAIR, I voted similarly, but developers from Germany disagreed.

> Afterwards, the A codes could be renumbered.

A-codes, once defined, cannot be changed, but they can become discontinued (and other, new A-codes may come in their place). You can read about this [here](http://opencaching.pl/okapi/services/attrs/attribute.html).

**Comment by wrygiel** [comment]
> > Both A70 and A71 refer to one attribute
>
> AFAIR, I voted similarly, but developers from Germany disagreed.

The reason was that their meanings are very similar, but not *exactly* the same. A70 means all kinds of children, while A71 means children of particular age group. Note, that currently only OCDE uses A71.

Also, OKAPI doesn't currently allow searching by A-code. We intended to developer separate set of S-codes for searching (each S-code would contain an *boolean expression* consisting of A-codes), but this project was kind of abandoned, due to lack of time and interest.

**Comment by wrygiel** [comment]
Also - great work with OCUK and updating the attributes file! I was on holidays throughout the month, so I have reviewed the changes only recently.
