### ISSUE TITLE
COG annotations not visible in C:GEO

### ISSUE THREAD

**Issue by DorotkaMakotka** [opencaching/okapi#533]
It would be desirable to include COG annotations (or other additional fields) in cache description displayed in C:GEO.

Sometimes COG annotations determine the conditions that need to be fulfilled to legitimately mark the cache as found. This applies e.g. to virtual caches where a photo is required - according to COG decision. Unfortunately it turned out that C:GEO users don't know about these additional conditions. It is still recommended for such annotations to remain logically separated from owner's description.

**Comment by following5** [comment]
What's a COG annotation, and where is it stored in OCPL database? What additional fields would you like to include?

**Comment by kojoty** [comment]
Hi @following5 
Do you know what is OCPL "COG"? If no - short desc:
polish oc-team has two subteams:
- RT - people responsible for technical side of service 
- COG - people elected by community of geocachers who represents the community and manages OCPL service in non-technical aspects

There is a little inconsistency in it but for now we have field "rr_commen" in table cache_desc - for sure it should be renamed to something like oc-team-note.

**Comment by following5** [comment]
Okay, I can add that to Okapi.

But currently I have no working OCPL develsite. Current OCPL code does not run on my CentOS 7 VM, so that I can test only common DE/PL features. Can you supply my with a working VirtualBox image for OCPL development?

**Comment by kojoty** [comment]
@following5 
The latest version of our dev virt. machine is described here: https://github.com/opencaching/opencaching-pl/wiki/vm_installation_and_usage_en_brief

This version is from beginning of this year but I hope there are not too much changes since that time.
If you encounter any problems with it give me know please.

**Comment by following5** [comment]
Thanks, OCPL develsite is now up and running. In Chrome it is fine; in Firefox I get this error when trying to login on th OC site: "Your browser does not accept cookies from OpenCaching.???" Cookies are enabled. Andy idea what's going on there?

**Comment by following5** [comment]
> $opt['cookie']['name'] = 'ocpl-devel';

Yeah, that did it.

**Comment by following5** [comment]
Fun!  :-D

**Comment by following5** [comment]
@DorotkaMakotka 
> It is still recommended for such annotations to remain logically separated from owner's description.

_Logical_ separation would mean that we return it separately from the owner's description through OKAPI. Then it will be up to all the app developers (there are more than just c:geo!) if they evaluate this information and display it. Not all will implement it, so the information will still not be visible to all users.

Wouldn't it be better to always append it to the owner's description text? E.g. append some separation line, a header "OC team comments" and then the comment text?

**Comment by mzylowski** [comment]
Jus note:
$opt['cookie']['name'] = 'ocpl-devel';
This is needed to add prefix for cookies. Without this, cookies from devel mixes with production OC coocieks and you got this warning. Actually this is expected. To workaround this I use private mode in my browser.

**Comment by following5** [comment]
We may do both:
* Add a separate field oc_team_comment;
* insert the team comment into the description text, included into `<div class="oc-team-comment">Comments by OC team:<br>...<hr></div>`.

So it will show up immediately in c:geo, but developers can choose to hide that and display it separately. And this will be fully compatible with OKAPI replication.

**Comment by following5** [comment]
New parameter `oc_team_comment` with three options
* `description` (default), will insert it into description as shown above,
* `separate`, will return it as separate field `oc_team_comment`
* `both`, does both.

Then use "both" for replication, and require developers to display it in the one or other way.

**Comment by following5** [comment]
While defining the interface I run into some issues:
* The `rr_comment` field stores finalized HTML for presentation on OCPL websites, including OCPL-specific CSS classes. We may want to replace them by something universal.
* It stores localized headers in the language that was active when the comment was written! Languages can be mixed within the same rr_comment. Okapi can do nothing about that.
* rr_comment is duplicated into all desc languages for the cache. If we return it as a language dictionary like the `description` and the `hint` field, it will contain lots redundant data.<br />Are there plans to enable separate rr_comments in different languages? Otherwise we may start without the dictionary and just return one rr_comment string.
* At the end of the description text, there is a note which attributes it to the geocache owner. The OC team comments must be clearly excluded from that and attributed to their authors, so that we won't run into copyright trouble. So we need to augment the attribution note, if rr_comment is present in the description field.
* It may confuse developers that there are OC team comment _logs_ and OC team comment _geocache annotations_. How can we explain to them what's the logical difference between both? When is the one used and when the other?

(And what's the difference between [add_rr_comment](https://github.com/opencaching/opencaching-pl/blob/master/add_rr_comment.php) and [add_octeam_comment](https://github.com/opencaching/opencaching-pl/blob/master/add_octeam_comment.php)?)

**Comment by kojoty** [comment]
@following5 
I made a little cleanup around rr_comment:
now the format of the log should be clear:
```
'<span class="ocTeamCommentHeader">'.tr('date').": $date, ".tr('add_by')." $userName:</span>" .
'<span class="ocTeamComment">'.$comment.'</span>'
```
but this is possible that there can be a serie of such comments

I think there are low chances that we will have comments in many languages - now it's even impossible - comment is just added to all descriptions "as-is" - so I think we can just take one common value - probably we should even migrate this field from cache_desc to caches in DB - but not now.

add_rr_comment was unused (legacy code) and is now removed.

**Comment by following5** [comment]
Me feeling still is that this mix of structured data and presentation is evil and will eventually cause trouble. It prevents to

* output the header lines in the locale (language, date format) of the _viewer_ instead of the one who wrote the comment. E.g. assume that there will be a consolidation of OCPL-based sites, with one serving multiple countries with different date formats (as OC.de already does);
* show the current user name of the team member (names may change) and link it to the user's profile, which allows easy email contact;
* safely applying some export format to the headers, e.g. make them bold for GPX export, (GPX clients surely will not implement the 'ocTeamCommentHeader' CSS!)
* delete individual comments.


Clean implementation would be to put it into a table oc_team_comment with the fields _cache_id_, _date_, _user_id_ and _comment_. Then do the HTML formatting only for output.  Old `rr_comment` field would be one-time migrated to new table.

Any chance to implement it that way in OCPL code?

**Comment by following5** [comment]
> Clean implementation would be to put it into a table  ...

But that would not work well with OKAPI replication of description texts. Okay then, let's go for the hack. ;)

**Comment by kojoty** [comment]
Yeah, I fully agree with you - there are many messy things in OCPL code and I often tolerate it because I can't clean everything at once.

Even the name of the column rr-comment is incorrect and legacy - we haven't had any RR for 3 years now - but for example changing the name of the column is quite complicated process if we apply sql patches manually on many nodes now. 

That field was added by someone as a "fast fix"  for problem. The fact is that there are no much ocTeam-comments - there are only ~500 for 50k+ of geocaches in db so this is one of so many problems to fix in our code. We are clean-up this huge mess for a few years by refactoring script by script but there are still a lot of work to do. 

If we will need to integrate it in future - yes- this will be one of hundred of problems!

My proposition is: for now let it go as-is. I hope one day we prepare separate table for such comments, and then we add additional fields to OKAPI response. 

For now we need this comments in OKAPI because some geocaches have important changes made by ocTeam and people are not aware of it looking for geocache with c:geo etc.  


and finally: @following5 I really appreciate your effort to maintain the OKAPI code clean and neat - great work - thanks!

**Comment by kojoty** [comment]
@following5 if you download our development virtual machine, there is DB snapshot which is a copy of prod. database with a short cleanup done by this https://github.com/opencaching/opencaching-pl/tree/master/docs/vm/sql_dump_trim script (generally we trim the logs to TFTC, and remove some of data which should stay private etc.) so all geocaches in that VM DB should be in same state at OCPL - so all geocaches with rr_coment in desc should be present at prod. site as well.

For fast reference tak a look at this:
https://opencaching.pl/viewcache.php?cacheid=10258
https://opencaching.pl/viewcache.php?cacheid=24581
https://opencaching.pl/viewcache.php?cacheid=40388

**Comment by following5** [comment]
```
'<span class="ocTeamCommentHeader">'.tr('date').": $date, ".tr('add_by')." $userName:</span>" .
'<span class="ocTeamComment">'.$comment.'</span>'
```
This span formatting does not work with c:geo. OKAPI does this  ...
```
                        $formatted_team_annotation = str_replace(
                            'class="ocTeamCommentHeader"',
                            'class="ocTeamCommentHeader" style="display: block; padding-top: 0.5em;"',
                            $row['oc_team_annotation']
                        );
```
before output, but still it looks like this:

![screenshot_20181112-104839b](https://user-images.githubusercontent.com/1614754/48340137-27981400-e66a-11e8-8d72-2d7e9e0a5836.jpg)

Can you change the `<span>` to `<div>`? [Did that](https://github.com/opencaching/okapi/commit/8bbdff00ea9e2187eaff70bd5908e73547ac0f30) with the "End of annotations", and it works.

**Comment by following5** [comment]
I have added the `<span>` => `<div>` replacement now in OKAPI. That's ugly, but produces nice team annotations in c:geo. :)

There is one c:geo issue left - the team annotations are displayed directly below the short description:

![screenshot_20181127-163808](https://user-images.githubusercontent.com/1614754/49092849-333b2b80-f263-11e8-9dcf-c7afc66f3045.jpg)

But that needs to be fixed in c:geo (use `oc_team_annotation=separate`, and put it above the short description). Whoever wants to have it fixed may open a c:geo issue.
