### ISSUE TITLE
Multiple OKAPI instances cannot be hosted on the same server

### ISSUE THREAD

**Issue by andrixnet** [opencaching/okapi#534]
Apparently two or more instances of OKAPI code a part of opencaching-pl cannot run simultaneously on the same server because some locking machanisms overlap.

At least `$lock_file = "/tmp/okapi-fatal-error-mode";` is not unique enough.

**Comment by andrixnet** [comment]
See https://github.com/opencaching/opencaching-pl/issues/1521 a well

**Comment by following5** [comment]
This lock file controls sending error notification emails to admins. It throttles email frequency to maximum 1 mail/second.  I think the overlap is fine here: If internal errors occur (nearly) simultaneously on multiple installations, they probably have the same origin; so it will be ok to send just one admin notification. In the unlikely case that unrelated errors occured, at least after fixing one installation messages will sent for the next installation when the problem reappears.

Did you experience any other issues with a multiple-instance setup? Otherwise we may close this.

**Comment by following5** [comment]
I assume that we don't have a problem here.
