### ISSUE TITLE
Migrate powertrail_ids search parameter to UUIDs

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#560]
The `powertrail_ids` parameter of search methods currently expects internal IDs. Not good. Meanwhile, an (indexed) `uuid` field was added to the `PowerTrail` table, and I think we should use that instead.

Probably noone external uses this feature, so we may try to completely migrate to UUIds; and throw an exception if integer numbers are passed. So far only a single ID is passed from the OCPL code, so there is no issue about GET parameter length limits.

A transition time of 18 hours would be needed, because of cached Okapi search sets.

**Comment by kojoty** [comment]
Btw. Powertrail is not a good name at all. We rather prefer to use name geopath in English - it is currently use and we would like to migrate the code to the single name: geopath.

**Comment by kojoty** [comment]
> We can rename that in OKAPI.
> 
> Oh, just noticed that you already started a refactoring from internal IDs to UUIds: https://github.com/opencaching/okapi/tree/feature/geopaths

I began works at geopath support in OKAPI but I decided to not continue it until refactor of geopaths in OCPL code - I'm going to make a deep refactoring of geopaths - I would like to change the way it works in many aspects - general vision is to make it much more similar to single geocache - this is longer story - there should be different states, sizes, attributes and types of geopath and more... I can provide the details if you want.

I would like to not add geopath support in OKAPI in current shape of geopaths because then (after the refactoring of geopaths) it will be necessary to change too many things what for sure will a backward compatibility problem.

> Btw, I am surprised that Geopaths are hidden when disabled. Why?

There are many "strange" things around geopath - this is developed in such way a few years ago and just works in this manner. I can't see any specific reason :) We are sure that it should be changed and I'm going to do that.

FYI. Now I'm working on logs refactor in OCPL - I need to prepare the new code which will be used for both geocaches and geopaths. There are lot of side works like for example new plugin for files upload or refactoring of the code responsible for pics uploaded to logs + current support, bugs fixing etc. - so in general - probably it takes next few months.

After that I will start refactoring of the geopaths module.

**Comment by following5** [comment]
Thanks for explanation!

> > Btw, I am surprised that Geopaths are hidden when disabled. Why?

> I can't see any specific reason :) We are sure that it should be changed and I'm going to do that.

Then we should postpone this issue until geopaths are refactored. The new `geopath_ids` parameter will behave different from the current `powertrail_ids`.

**Comment by following5** [comment]
The `powertrail_ids` search option is deprecated now. Currently there is nothing more to do in OKAPI.
