### ISSUE TITLE
Make download link(s) vissible on OKAPI search result page

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/okapi#584]
After a search the result can be downloaded as OKAPI GPX. Each smaller GPX file can be downloaded by clicking on it and if there are a lot of smaller GPX files it is a lot of work just to download them all.
For this a add-on can be used like "Snap Links" but for our GPX result page is is not useful because there are no links visible.
![selectie_315](https://user-images.githubusercontent.com/1060518/54030797-088b3800-41ad-11e9-8140-b874c7a51a5b.png)

Could it be possible to make the links visible when hoover the mouse on a link like another GPX download has?

![selectie_318](https://user-images.githubusercontent.com/1060518/54031053-e3e39000-41ad-11e9-9512-4051cc33394f.png)

**Comment by following5** [comment]
Yep, that's easy. It actually is an OCPL task, not OKAPI, but I will take it from here.

**Comment by following5** [comment]
This does not work as expected. The reason is that there are no href's, but the download links work by onclick &  POST to /lib/okapi_gpx.php.This is because OCPL code passes a list of all OC-codes to be downloaded, which is too long and nasty for a GET.

Would need some other mechanism to pass the cache code list to okapi_gpx.php.

@harrieklomp 
Can you open a new OCPL issue for this, with reference to this OKAPI issue? It needs to be done in OCPL code.
